version: '3.7'
services:
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - app

  fluentd:
    image: pistacks/fluentd-influxdb
    ports:
      - '24224:24224'
    networks:
      - app

  influxdb:
    image: influxdb
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=logs
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - /influxdb/data:/var/lib/influxdb'
    networks:
      - app
    
  web:
    image: nginx
    ports:
      - 80:80
    networks:
      - app
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.{{index .Service.Labels "com.docker.stack.namespace"}}.{{.Service.Name}}

networks:
  app:
    driver: overlay
    name: app
